name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Change to backend directory
        run: cd backend  # Or 'frontend' if your package.json is there
      
      - name: Install Dependencies
        run: npm install --verbose
        working-directory: backend  # Specify the correct directory

      - name: Run Tests
        run: npm test
        working-directory: backend
